### PR TITLE
New rules

### PR DESCRIPTION
**Pull request by Inzanit**
Discuss the new rules here. As per meeting #1 

Discussion will be open, at the latest, until ~~2020-02-08~~ 2020-02-16 22:00 UTC.

### CODE REVIEW

**Comment by svengeance** [comment]
`Discussion of security topics is up to the discretion of staff. Please be mindful of how you phrase your question (e.g. “How can I protect my web app from SQL injection?” is ok, but “What kind of input could break my web app?” is not).`

I don't like the example here. I think it's a perfectly valid question for a user to post a sample of their controller and service layer, and ask if they're correctly sanitizing their input.

**Comment by mastorm** [comment]
> “What kind of input could break my web app?”

Im with @svengeance here. Maybe just replace "my" with "a third party"?

**Comment by Inzanit** [comment]
> `Discussion of security topics is up to the discretion of staff. Please be mindful of how you phrase your question (e.g. “How can I protect my web app from SQL injection?” is ok, but “What kind of input could break my web app?” is not).`
> 
> I don't like the example here. I think it's a perfectly valid question for a user to post a sample of their controller and service layer, and ask if they're correctly sanitizing their input or if there exists input which would break their web app.

This explicit rule is being removed and will be up to staff discretion.

**Comment by mastorm** [comment]
Oooooooooooo svengeance misread the git diff then

**Comment by svengeance** [comment]
Would like to formalize that Inz is a dingus. That is all. Carry on.

**Comment by svengeance** [comment]
On the real -

> 3) Posts offering money for help, referral links or job postings are not allowed.

This should be changed to _any_ compensation. Otherwise, steam games, handies, nitro boosts...all are valid non-monetary payments

**Comment by ratscribbles** [comment]
where is the old rule 6?

> 6) Using the member list of this guild to target users' private messages in order to break rules is forbidden.

pls have this be explicit as its own rule in some form.

request to swap the order of sentences in rule 1 to:

> 1. Personal attacks, harassment, and hate speech will not be tolerated. Be civil.

so it's the first thing seen when reading and matches the style of the other rules after rule 0 ([forbidden] => [detail])

**Comment by HurricanKai** [comment]
Regarding rule 5
I think this relies too much on prior knowledge. 
Imo it would make sense to clarify that NSFW = not safe for work
And how to mark / spoiler
 Also, maybe explicitly disallow gore too

**Comment by HurricanKai** [comment]
I'm also no fan of 4, I can't quite imagine what's meant here tbh.

**Comment by UchuuHamster** [comment]
> Any activity that may endanger your life or lead to your physical harm is forbidden.
I hate to nitpick here but I believe further clarification is required. There are many activities that can endanger life and lead to physical harm. The rule should clarify that the *excessive encouragement* of activities that lead to the latter should be forbidden.

**Comment by NullEntity** [comment]
> There are many activities that can endanger life and lead to physical harm. The rule should clarify that the _excessive encouragement_ of activities that lead to the latter should be forbidden.

@UchuuHamster can you provide examples of what might be banned under the proposed rules, but allowed under your version?

**Comment by UchuuHamster** [comment]
@NullEntity for example, on the topic of alcohol...

Things along the lines of "I went out last night and had a drink with my friends" is acceptable in my opinion, as it is a casual and safe conversation.

However, something such as "I was wasted yesterday, three shots of tequila and bottomless booze! Man, I can't wait to drown myself in that good stuff again" is stretching the limits and may directly or indirectly encourage others to do the same, which could seriously risk their health. 

Of course, all of his is hypothetical and just to demonstrate my point.

**Comment by Scott-Caldwell** [comment]
> Things along the lines of "I went out last night and had a drink with my friends" is acceptable in my opinion, as it is a casual and safe conversation.

I'm not sure I understand how that would violate a rule against endangering lives or leading to physical harm. Would you be able to clarify how someone could interpret it that way?

**Comment by UchuuHamster** [comment]
> I'm not sure I understand how that would violate a rule against endangering lives or leading to physical harm. Would you be able to clarify how someone could interpret it that way?

Discord's ToS states that their minimum age for service is 13 and there is a small chance there are younger people in the server. My only worry is that in the unlikely event of an excessive discussion or glamorising the use of alcohol (and other "things" such as drugs, self-harm, and suicide) could directly or indirectly lead to an unsuspecting person harming themselves. This may not necessarily be a young person but also a person who is going through extreme difficulties in their lives. 

Then one may state that "it's the internet, stuff like this is bound to happen," to which I say, such discussion on the above themes shouldn't happen on a programming server in my humble opinion anyways.

**Comment by HurricanKai** [comment]
As a result of https://discordapp.com/channels/143867839282020352/175609431478894594/673996565391736871 I'd like to bring up whether we confirm to Discord ToS because it matches our principals, or because we want to prevent the guild getting in trouble (as D. Mentia noted)
This might also just be worth considering for the codex, unsure. Because if smelling something, should we try to help without breaking ToS directly, or look whether the question relates to something breaking ToS, terminating the question. 
Also, if that user was to reword his/her question in such a way it does not mention any ToS breaking behaviour, do we help? This isn't clear currently imo.

**Comment by Foxtrek64** [comment]
Per discussion in #9, I do believe that rule number 6 should remain.

> Using the member list of this guild to target users' private messages in order to break rules is forbidden

This will supplement a note that users should prefer seeking support in public channels, though the exact wording on this is still being discussed.

**Comment by Inzanit** [comment]
Closing this out for now, it's stale and rules have not been updated. We will be opening a new issue/PR for this in the future.

**Pull request closed without merging**
